### ISSUE TITLE
I built a git action for wake

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#433]
The example is here: https://github.com/davidmlw/example-chisel-iotester-wake. The action is here https://github.com/davidmlw/jdk-wake. To use the jdkwake action:

```
    - name: Compose workspace
      uses: sifive/wit/actions/wit@master
      with:
        command: init
        arguments: |
          workspace
          -a git@github.com:davidmlw/example-chisel-iotester-wake.git::jar
        force_github_https: true

    - name: Build workspace
      uses: davidmlw/jdk-wake@master
      with:
        arguments: all
```

Currently I dont know how to pass "string" arguments to wake, so " -x '5+7' " is not working.

**Comment by terpstra** [comment]
Could you perhaps elaborate a bit more? What is this?

**Comment by davidmlw** [comment]
Oh, I was inspired by wit github actions, and implement a wake action. With wake action, users can trigger github to run a build in a wit/wake workspace at the cloud. That would be more easier for Chisel/Rocket-chip users to communicate based on execution results. See one execution example here: https://github.com/davidmlw/example-chisel-iotester-wake/runs/695043157?check_suite_focus=true.

This example has two versions, jar depend and src depend. jar version will use chisel3 from published package, and src version will build everything from scratch. 

The wake action is here https://github.com/davidmlw/jdk-wake. I would propose merge this to Wake if you think it is doable.

**Comment by terpstra** [comment]
FYI, I now know what github actions are. This is the one I'm rolling out all over:
  https://github.com/sifive/environment-blockci-sifive/pull/15

```yml
  test:
    name: Scala compile
    runs-on: ubuntu-latest

    steps:
    - name: Wit Init
      uses: sifive/wit/actions/init@v0.13.2
      with:
        environment: git@github.com:sifive/environment-blockci-sifive.git::0.7.0

    - name: Run wake scala compile
      uses: sifive/environment-blockci-sifive/actions/wake@0.7.0
      with:
        command: -x 'compileScalaModule myScalaModule | getPathResult'
```
